export { default as ComExplain } from './ComExplain';
export { default as Signup } from './Signup';
export { default as Main } from './Main';
export { default as Login } from './Login';
export { default as ModifyInfo } from './ModifyInfo';
export { default as Community } from './Community';
export { default as IDK } from './IDK';
export { default as MobExplain } from './MobExplain';
export { default as NotFound } from './NotFound';
